[alias]
scaffold = "run --quiet --release -- scaffold"
download = "run --quiet --release -- download"

solve = "run --quiet --release -- solve"
all = "run --quiet --release -- all"
time = "run --quiet --release -- all --release --time"

[env]
AOC_YEAR = "2023"
